language: node_js
node_js:
  - "0.12"

cache:
  directories:
    - node_modules

#    gulp config
before_script:
  - npm install -g gulp
  - npm install -g bower
  - bower install -f
script:
  - gulp

deploy:
  provider: heroku
  app:
    master: flappernews2016
    dev: flappernews2016-stg
    feature-integracion-continua: flappernews2016-stg
  api_key:
    secure: $HEROKU_API_KEY
